convert Interop to Truffle Libraries
NVIDIA/grcuda pull request #1
Opened 2019-09-12 16:04 UTC by lukasstadler

These changes mainly update the interop code in grCUDA (in DeviceArray, etc.) to the new interop API in Truffle.
Additionally, there's some other minor updates:
- Modify the makefile that runs the parser generator to generate only the necessary files (no listeners, etc.) and to pre-process all files at once (fixes build problems).
- Don't store the context in the language, and use `@CachedContext(GrCUDALanguage.class)` in the right places.

2019-09-12 22:29 UTC, muellren requested changes
There is one bug in DeviceArrayFunction. There is a new DeviceArrayTest Unit test I plan to merge soon.

2019-09-12 22:29 UTC, muellren commented on projects/com.nvidia.grcuda/src/com/nvidia/grcuda/functions/DeviceArrayFunction.java
> +        String typeName = expectString(arguments[1], "first argument of DeviceArray must be string (type name)");
BUG: Must be arguments[0] instead of argument one.

2019-09-13 09:59 UTC, lukasstadler commented on projects/com.nvidia.grcuda/src/com/nvidia/grcuda/functions/DeviceArrayFunction.java
> +        String typeName = expectString(arguments[1], "first argument of DeviceArray must be string (type name)");
ah, of course - I had that in a separate commit that I forgot to cherry pick.

2019-09-13 10:28 UTC, muellren approved these changes
Thanks, these changes look good to me. The polyglot language tests are passing as well. 
Go ahead, you should be able to merge the PR if this is setup correctly.

2019-09-13 11:01 UTC, merged