consistently use GrCUDAException and GrCUDAInternalException, remove deprecated parse API usages
NVIDIA/grcuda pull request #19
Opened 2020-03-03 14:09 UTC by lukasstadler

This PR pulls out the changes to exception handling (don't throw `RuntimeExceptions`) from https://github.com/NVIDIA/grcuda/pull/18.
It also changes the deprecated `parse` calls to `parseInternal`, adds some minor code simplifications in `CUDARuntime`, and replaces the usages of `System.err` in `NVRuntimeCompiler` with `TruffleLanguage.Env.err`.

2020-03-03 18:42 UTC, muellren requested changes
Except for a minor issue on `CUDARuntime.java:309`. the changes look good to me.

2020-03-03 18:42 UTC, muellren commented on projects/com.nvidia.grcuda/src/com/nvidia/grcuda/gpu/CUDARuntime.java
> +            throw new GrCUDAException("expected return code as Integer object in " + function + ", got " + result.getClass().getName());
I think there is a problem with `String... function` which turns in to a `String[]` and subsequently into something like `"[Ljava.langString;...."`.

2020-03-03 18:42 UTC, muellren commented on projects/com.nvidia.grcuda/src/com/nvidia/grcuda/gpu/CUDARuntime.java
> +                            "expected return code as Integer object in " + GrCUDAException.format(function) + ", got " +
Here, the string gets properly formatted on L309 it is not.

2020-03-04 12:35 UTC, lukasstadler commented
Thanks for the hints, I fixed the two places that were missing the call to `format`. Should be ready to merge from my point of view.

2020-03-04 12:38 UTC, muellren approved these changes
Fixes issues, thanks.

2020-03-04 12:47 UTC, merged