add missing TruffleBoundary and transferToInterpreter
NVIDIA/grcuda pull request #9
Opened 2019-09-27 10:02 UTC by lukasstadler

These changes are enough to allow creating a native image with support for grCUDA.
Unfortunately, it's not quite obvious how to build and use a polyglot image:
```
bin/gu rebuild-images libpolyglot -cp <path-to>/grcuda.jar
```
will enable grCUDA in `bin/node --polyglot.

```
bin/gu rebuild-images polyglot -cp <path-to>/grcuda.jar
```
will enable grCUDA in `bin/js --polyglot.

2019-09-30 09:19 UTC, muellren requested changes
mx checkstyle fails (no spaces between imports).

2019-09-30 09:23 UTC, muellren commented
Does not seem to work for me.

```
gu rebuild-images polyglot -cp mxbuild/dists/jdk1.8/grcuda.jar
js --polyglot
> const DeviceArray = Polyglot.eval('grcuda', 'DeviceArray')
Error: No language for id grcuda found. Supported languages are: [js, llvm, python, ruby]
        at <js> :program(<shell>:1:1:20-57)
```
```
gu rebuild-images libpolyglot -cp mxbuild/dists/jdk1.8/grcuda.jar
node --polyglot
> const DeviceArray = Polyglot.eval('grcuda', 'DeviceArray')
Error: No language for id grcuda found. Supported languages are: [js, llvm, python, ruby]
    at Object.eval (native)
```
I did also copy the grcuda.jar into `languages/grcuda`.

2019-09-30 12:28 UTC, lukasstadler commented
Could you please try the `gu rebuild-images` commands with an absolute path for the grcuda.jar file?

2019-09-30 15:10 UTC, muellren commented
> Could you please try the `gu rebuild-images` commands with an absolute path for the grcuda.jar file?

`bin/gu rebuild-image -cp <absolute-path-to>/grcuda.jar` works.

2019-10-04 12:30 UTC, lukasstadler commented
> mx checkstyle fails (no spaces between imports).

I think I'll have to resolve this by removing the offending check from the checkstyle configuration, since it clashes with what the eclipse formatting/organize import does.

2019-10-10 13:07 UTC, muellren approved these changes

2019-10-10 13:09 UTC, merged